version: "3.3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - db
  db:
    image: "mysql:8.0"
    environment:
      MYSQL_ROOT_PASSWORD: Eyad@Amer2022
      MYSQL_DATABASE: geekprofile
      MYSQL_USER: EyadAmer
      MYSQL_PASSWORD: Eyad@Amer2022
    volumes:
      - "db_data:/var/lib/mysql"
volumes:
  db_data:

